### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yjslzx** [qiaoyu-tan/S2GAE#1]
hello, I would like to ask for advice.
In the node classification problem, the dataset used is Cora
Every time I run it, it prompts me with this problem, how should I change it?
`
RuntimeError: The size of tensor a (0) must match the size of tensor b (4609) at non-singleton dimension 0
`

**Comment by AILUOMANGALAOSHI** [comment]
> hello, I would like to ask for advice.

It is difficult to provide an exact explanation without specific details about the function calls that resulted in the error. However, since the error message indicates a tensor of size 0, one possibility is that your dataset failed to load successfully. In deep learning, it is common to load training, validation, or test data into models for training or evaluation. If the dataset fails to load, various errors can occur, including tensor size 0 errors. Therefore, when processing data, ensure that the correct dataset path is set and the appropriate method is used for loading the dataset. You can use print statements or a debugger to check if the data has been loaded correctly. Additionally, check if the dataset contains empty or insufficient samples, and handle exceptions carefully during data processing. Problems during data processing may lead to tensor size 0 errors.

**Comment by yjslzx** [comment]
Thank you very much for your answer, it is indeed a problem in data processing, thanks again

**Comment by yjslzx** [comment]
Thank you very much for your answer, it is indeed a problem in data processing, I will try again, thanks again
